version: '3.7'

services:
  banco:
    image: mysql
    container_name: ct-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./api/db/data:/var/lib/mysql
    restart: always

  api:
    build: "./api"
    container_name: ct-node
    restart: always
    volumes:
      - ./api:/home/api
    ports:
      - "9001:9001"
    depends_on:
      - banco

  web:
    image: "php:7.4-apache"
    container_name: ct-php
    restart: always
    volumes:
      - ./api/website:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - api
